#!/usr/bin/env bash

set -x
export CMD_PATH=$(cd `dirname $0`; pwd)
export PROJECT_NAME="${CMD_PATH##*/}"
echo $PROJECT_NAME
cd $CMD_PATH
ls -al
apt update -y
apt upgrade -y

function pkg_install_remove()
{
	cd $CMD_PATH
	while read pkg
	do
  		echo $pkg
  		apt install -y --no-install-recommends $pkg
	done < packages.list.txt

	while read pkg
	do
 		echo $pkg
  		apt install -y $pkg
	done < remove.list.txt
}
pkg_install_remove

apt install -y exfatprogs
apt install -y debootstrap 
apt install -y squashfs-tools
apt install -y xorriso
apt install -y isolinux
apt install -y syslinux-efi
apt install -y grub-pc-bin
apt install -y grub-efi-amd64-bin
apt install -y grub-efi-ia32-bin
apt install -y mtools
apt install -y dosfstools
apt install -y rsync 
apt install -y qemu-system-x86
apt install -y docker.io 
# apt install -y docker-compose 
# curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o /usr/bin/docker-compose
apt install -y golang
apt install -y maven
apt install -y tree
apt install -y extlinux
apt install -y kpartx
apt install -y p7zip-full grub2-common mtools xorriso squashfs-tools-ng jq
apt install -y cloud-utils
apt install -y deepin-terminal
apt install -y caddy
apt install -y repo
apt install -y ostree
apt install -y wget 
apt install -y gpg
apt install -y adb
apt install -y fastboot
apt install -y ruby
apt install -y net-tools
apt install -y ssh
apt install -y ntpdate
systemctl enable docker
systemctl enable ssh



apt install caddy -y

apt autoremove -y

apt remove --purge -y $(dpkg -l | grep linux-image | awk '{print $2}')
dpkg -l | grep linux-image | awk '{print $2}'
apt update -y
apt upgrade -y
apt -y install --no-install-recommends linux-image-amd64

echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config

mkdir -p /etc/sudoers.d
echo "www ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/www-nopassword
echo "runner ALL=(ALL) NOPASSWD: ALL"   > /etc/sudoers.d/runner-nopassword
chmod 750 /etc/sudoers.d/www-nopassword
chmod 750 /etc/sudoers.d/runner-nopassword
chmod 750 /etc/sudoers.d/
cat /etc/passwd



pip install selenium-wire --break-system-packages
pip install scrapeops-scrapy --break-system-packages
pip install scrapeops-scrapy-proxy-sdk --break-system-packages



apt install chromium-driver  -y
apt install chromium  -y


apt update -y
apt upgrade -y
apt autoremove -y
apt clean -y

# https://blog.csdn.net/qq_21891743/article/details/132818491
apt install -y sysbench
sysbench --version


update_install_remove_clean v23q4 remove

acl
adduser
adwaita-icon-theme
alsa-topology-conf
alsa-ucm-conf
alsa-utils
amd64-microcode
anacron
anthy
anthy-common
apparmor
apt
apt-transport-https
apt-utils
arch-test
aspell
aspell-am
aspell-ar
aspell-ar-large
aspell-bg
aspell-ca
aspell-cs
aspell-cy
aspell-da
aspell-de
aspell-el
aspell-en
aspell-eo
aspell-es
aspell-et
aspell-eu
aspell-fa
aspell-fr
aspell-ga
aspell-gl-minimos
aspell-he
aspell-hr
aspell-hu
aspell-is
aspell-it
aspell-kk
aspell-ku
aspell-lt
aspell-lv
aspell-nl
aspell-no
aspell-pl
aspell-pt-br
aspell-pt-pt
aspell-ro
aspell-ru
aspell-sk
aspell-sl
aspell-sv
aspell-tl
aspell-uk
atmel-firmware
atril
atril-common
at-spi2-common
at-spi2-core
avahi-autoipd
avahi-daemon
avahi-utils
base-files
base-passwd
bash
bc
binutils
binutils-common
binutils-x86-64-linux-gnu
bluez
bluez-firmware
bsdextrautils
bsd-mailx
bsdutils
btrfs-progs
bubblewrap
build-essential
busybox
bzip2
ca-certificates
ca-certificates-java
cgroupfs-mount
chromium
chromium-common
chromium-sandbox
code
coinor-libcbc3
coinor-libcgl1
coinor-libclp1
coinor-libcoinmp1v5
coinor-libcoinutils3v5
coinor-libosi1v5
colord
colord-data
console-setup
console-setup-linux
containerd
coreutils
cpio
cpp
cpp-12
criu
cron
cron-daemon-common
cryptsetup-bin
culmus
cups
cups-browsed
cups-client
cups-common
cups-core-drivers
cups-daemon
cups-filters
cups-filters-core-drivers
cups-ipp-utils
cups-pk-helper
cups-ppdc
cups-server-common
curl
dahdi-firmware-nonfree
dash
dbus
dbus-bin
dbus-daemon
dbus-session-bus-common
dbus-system-bus-common
dbus-user-session
dbus-x11
dconf-cli
dconf-gsettings-backend
dconf-service
debconf
debconf-i18n
debian-archive-keyring
debianutils
debootstrap
default-jdk
default-jdk-headless
default-jre
default-jre-headless
desktop-base
desktop-file-utils
dictionaries-common
diffutils
dirmngr
dmidecode
dmsetup
dnsmasq-base
dns-root-data
docker-compose
docker.io
dosfstools
dpkg
dpkg-dev
e2fsprogs
efibootmgr
eject
emacsen-common
enchant-2
espeak-ng-data
exfalso
exfatprogs
exim4-base
exim4-config
exim4-daemon-light
exo-utils
fakeroot
fdisk
file
findutils
firefox-esr
firefox-esr-l10n-ar
firefox-esr-l10n-ast
firefox-esr-l10n-be
firefox-esr-l10n-bg
firefox-esr-l10n-bn
firefox-esr-l10n-bs
firefox-esr-l10n-ca
firefox-esr-l10n-cs
firefox-esr-l10n-cy
firefox-esr-l10n-da
firefox-esr-l10n-de
firefox-esr-l10n-el
firefox-esr-l10n-en-gb
firefox-esr-l10n-eo
firefox-esr-l10n-es-ar
firefox-esr-l10n-es-cl
firefox-esr-l10n-es-es
firefox-esr-l10n-es-mx
firefox-esr-l10n-et
firefox-esr-l10n-eu
firefox-esr-l10n-fa
firefox-esr-l10n-fi
firefox-esr-l10n-fr
firefox-esr-l10n-ga-ie
firefox-esr-l10n-gl
firefox-esr-l10n-gu-in
firefox-esr-l10n-he
firefox-esr-l10n-hi-in
firefox-esr-l10n-hr
firefox-esr-l10n-hu
firefox-esr-l10n-id
firefox-esr-l10n-is
firefox-esr-l10n-it
firefox-esr-l10n-ja
firefox-esr-l10n-kk
firefox-esr-l10n-km
firefox-esr-l10n-kn
firefox-esr-l10n-ko
firefox-esr-l10n-lt
firefox-esr-l10n-lv
firefox-esr-l10n-mk
firefox-esr-l10n-mr
firefox-esr-l10n-nb-no
firefox-esr-l10n-ne-np
firefox-esr-l10n-nl
firefox-esr-l10n-nn-no
firefox-esr-l10n-pa-in
firefox-esr-l10n-pl
firefox-esr-l10n-pt-br
firefox-esr-l10n-pt-pt
firefox-esr-l10n-ro
firefox-esr-l10n-ru
firefox-esr-l10n-si
firefox-esr-l10n-sk
firefox-esr-l10n-sl
firefox-esr-l10n-sq
firefox-esr-l10n-sr
firefox-esr-l10n-sv-se
firefox-esr-l10n-ta
firefox-esr-l10n-te
firefox-esr-l10n-th
firefox-esr-l10n-tr
firefox-esr-l10n-uk
firefox-esr-l10n-vi
firefox-esr-l10n-zh-cn
firefox-esr-l10n-zh-tw
firmware-amd-graphics
firmware-ast
firmware-ath9k-htc
firmware-atheros
firmware-bnx2
firmware-bnx2x
firmware-brcm80211
firmware-cavium
firmware-intel-sound
firmware-ipw2x00
firmware-ivtv
firmware-iwlwifi
firmware-libertas
firmware-linux
firmware-linux-free
firmware-linux-nonfree
firmware-misc-nonfree
firmware-myricom
firmware-netronome
firmware-netxen
firmware-qlogic
firmware-realtek
firmware-realtek-rtl8723cs-bt
firmware-siano
firmware-sof-signed
firmware-zd1211
fontconfig
fontconfig-config
fonts-arundina
fonts-beng
fonts-beng-extra
fonts-bpg-georgian
fonts-dejavu
fonts-dejavu-core
fonts-dejavu-extra
fonts-deva
fonts-deva-extra
fonts-droid-fallback
fonts-dzongkha
fonts-farsiweb
fonts-font-awesome
fonts-freefont-ttf
fonts-gargi
fonts-gujr
fonts-gujr-extra
fonts-guru
fonts-guru-extra
fonts-hosny-amiri
fonts-hosny-thabit
fonts-ipafont
fonts-ipafont-gothic
fonts-ipafont-mincho
fonts-kacst
fonts-kacst-one
fonts-kalapi
fonts-khmeros
fonts-lato
fonts-liberation
fonts-liberation2
fonts-lohit-beng-assamese
fonts-lohit-beng-bengali
fonts-lohit-deva
fonts-lohit-gujr
fonts-lohit-guru
fonts-lohit-knda
fonts-lohit-mlym
fonts-lohit-taml
fonts-lohit-taml-classical
fonts-lohit-telu
fonts-mathjax
fonts-mlym
fonts-nakula
fonts-nanum
fonts-noto
fonts-noto-cjk
fonts-noto-cjk-extra
fonts-noto-color-emoji
fonts-noto-core
fonts-noto-extra
fonts-noto-mono
fonts-noto-ui-core
fonts-noto-ui-extra
fonts-noto-unhinted
fonts-opensymbol
fonts-quicksand
fonts-sahadeva
fonts-samyak-deva
fonts-samyak-gujr
fonts-samyak-mlym
fonts-samyak-taml
fonts-sarai
fonts-sil-abyssinica
fonts-sil-andika
fonts-sil-annapurna
fonts-sil-scheherazade
fonts-smc
fonts-smc-anjalioldlipi
fonts-smc-chilanka
fonts-smc-dyuthi
fonts-smc-gayathri
fonts-smc-karumbi
fonts-smc-keraleeyam
fonts-smc-manjari
fonts-smc-meera
fonts-smc-rachana
fonts-smc-raghumalayalamsans
fonts-smc-suruma
fonts-smc-uroob
fonts-symbola
fonts-taml
fonts-telu
fonts-telu-extra
fonts-teluguvijayam
fonts-thai-tlwg
fonts-tlwg-garuda
fonts-tlwg-garuda-ttf
fonts-tlwg-kinnari
fonts-tlwg-kinnari-ttf
fonts-tlwg-laksaman
fonts-tlwg-laksaman-ttf
fonts-tlwg-loma
fonts-tlwg-loma-ttf
fonts-tlwg-mono
fonts-tlwg-mono-ttf
fonts-tlwg-norasi
fonts-tlwg-norasi-ttf
fonts-tlwg-purisa
fonts-tlwg-purisa-ttf
fonts-tlwg-sawasdee
fonts-tlwg-sawasdee-ttf
fonts-tlwg-typewriter
fonts-tlwg-typewriter-ttf
fonts-tlwg-typist
fonts-tlwg-typist-ttf
fonts-tlwg-typo
fonts-tlwg-typo-ttf
fonts-tlwg-umpush
fonts-tlwg-umpush-ttf
fonts-tlwg-waree
fonts-tlwg-waree-ttf
fonts-ukij-uyghur
fonts-unifont
fonts-unikurdweb
fonts-urw-base35
fonts-vlgothic
fonts-yrsa-rasa
fortune-mod
fortunes-debian-hints
fortunes-it
fuse3
g++
g++-12
gcc
gcc-12
gcc-12-base
gcr
gdisk
geoclue-2.0
gettext-base
ghostscript
gimp-data
gimp-help-common
gimp-help-sv
gir1.2-atk-1.0
gir1.2-atspi-2.0
gir1.2-freedesktop
gir1.2-gdkpixbuf-2.0
gir1.2-glib-2.0
gir1.2-gst-plugins-base-1.0
gir1.2-gstreamer-1.0
gir1.2-gtk-3.0
gir1.2-gtksource-3.0
gir1.2-handy-1
gir1.2-harfbuzz-0.0
gir1.2-ibus-1.0
gir1.2-javascriptcoregtk-4.0
gir1.2-keybinder-3.0
gir1.2-notify-0.7
gir1.2-packagekitglib-1.0
gir1.2-pango-1.0
gir1.2-polkit-1.0
gir1.2-secret-1
gir1.2-soup-2.4
gir1.2-webkit2-4.0
gir1.2-wnck-3.0
git
git-man
glib-networking
glib-networking-common
glib-networking-services
gnome-accessibility-themes
gnome-icon-theme
gnome-keyring
gnome-keyring-pkcs11
gnome-themes-extra
gnome-themes-extra-data
gnupg
gnupg-l10n
gnupg-utils
goldendict
gpg
gpg-agent
gpgconf
gpgsm
gpgv
gpg-wks-client
gpg-wks-server
grep
groff-base
grub2-common
grub-common
grub-efi-amd64
grub-efi-amd64-bin
grub-efi-amd64-signed
grub-efi-ia32-bin
grub-pc-bin
gsettings-desktop-schemas
gsfonts
gstreamer1.0-alsa
gstreamer1.0-gl
gstreamer1.0-gtk3
gstreamer1.0-libav
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-base
gstreamer1.0-plugins-good
gstreamer1.0-plugins-ugly
gstreamer1.0-x
gtk2-engines-pixbuf
gtk-update-icon-cache
gvfs
gvfs-common
gvfs-daemons
gvfs-libs
gzip
hdmi2usb-fx2-firmware
hicolor-icon-theme
hostname
hspell
hspell-gui
hunspell
hunspell-ar
hunspell-be
hunspell-bg
hunspell-bs
hunspell-ca
hunspell-cs
hunspell-da
hunspell-de-at
hunspell-de-ch
hunspell-de-de
hunspell-el
hunspell-en-gb
hunspell-en-us
hunspell-eu
hunspell-fr
hunspell-fr-classical
hunspell-gl
hunspell-gl-es
hunspell-gu
hunspell-hi
hunspell-hr
hunspell-hu
hunspell-id
hunspell-is
hunspell-it
hunspell-kk
hunspell-kmr
hunspell-ko
hunspell-lt
hunspell-lv
hunspell-ml
hunspell-ne
hunspell-nl
hunspell-pl
hunspell-pt-br
hunspell-pt-pt
hunspell-ro
hunspell-ru
hunspell-si
hunspell-sl
hunspell-sr
hunspell-sv
hunspell-sv-se
hunspell-te
hunspell-th
hunspell-vi
hyphen-de
hyphen-en-us
hyphen-hr
hyphen-hu
hyphen-lt
i2c-tools
i965-va-driver
iamerican
ibrazilian
ibritish
ibulgarian
ibus
ibus-data
ibus-gtk
ibus-gtk3
ibus-gtk4
ibus-hangul
ibverbs-providers
icatalan
idanish
idutch
ienglish-common
ifrench-gut
ifupdown
ihungarian
iio-sensor-proxy
iitalian
ilithuanian
imagemagick-6-common
im-config
indi-dsi
ingerman
init
initramfs-tools
initramfs-tools-core
init-system-helpers
inorwegian
intel-media-va-driver
intel-microcode
ipolish
iportuguese
ipp-usb
iproute2
iptables
iputils-ping
ipxe-qemu
irussian
isc-dhcp-client
isc-dhcp-common
iso-codes
isolinux
ispanish
ispell
iswiss
iucode-tool
iw
ixo-usb-jtag
java-common
javascript-common
kasumi
kbd
keyboard-configuration
klibc-utils
kmod
less
liba52-0.7.4
libaa1
libaacs0
libabsl20220623
libabw-0.1-1
libacl1
libaio1
libalgorithm-diff-perl
libalgorithm-diff-xs-perl
libalgorithm-merge-perl
libamd2
libanthy1
libanthyinput0
libao4
libao-common
libaom3
libapparmor1
libapt-pkg6.0
libarchive13
libargon2-1
libasan8
libasound2
libasound2-data
libasound2-plugins
libaspell15
libass9
libassuan0
libasyncns0
libatasmart4
libatk1.0-0
libatk-adaptor
libatk-bridge2.0-0
libatkmm-1.6-1v5
libatk-wrapper-java
libatk-wrapper-java-jni
libatomic1
libatopology2
libatrildocument3
libatrilview3
libatspi2.0-0
libattr1
libaudio2
libaudit1
libaudit-common
libauthen-sasl-perl
libavahi-client3
libavahi-common3
libavahi-common-data
libavahi-core7
libavahi-glib1
libavc1394-0
libavcodec59
libavfilter8
libavformat59
libavif15
libavutil57
libayatana-appindicator3-1
libayatana-ido3-0.4-0
libayatana-indicator3-7
libbabl-0.1-0
libbdplus0
libbinutils
libblas3
libblkid1
libblockdev2
libblockdev-crypto2
libblockdev-fs2
libblockdev-loop2
libblockdev-part2
libblockdev-part-err2
libblockdev-swap2
libblockdev-utils2
libbluetooth3
libbluray2
libboost-filesystem1.74.0
libboost-iostreams1.74.0
libboost-locale1.74.0
libboost-regex1.74.0
libboost-thread1.74.0
libbox2d2
libbpf1
libbrlapi0.8
libbrotli1
libbs2b0
libbsd0
libburn4
libbz2-1.0
libc6
libc6-dev
libcaca0
libcacard0
libcairo2
libcairo-gobject2
libcairo-gobject-perl
libcairomm-1.0-1v5
libcairo-perl
libcairo-script-interpreter2
libcaja-extension1
libcamd2
libcanberra0
libcanberra-gtk3-0
libcanberra-gtk3-module
libcap2
libcap2-bin
libcap-ng0
libcapstone4
libc-bin
libcbor0.8
libcc1-0
libccolamd2
libc-dev-bin
libc-devtools
libcdio19
libcdparanoia0
libcdr-0.1-1
libcfitsio10
libchewing3
libchewing3-data
libcholmod3
libchromaprint1
libcjson1
libc-l10n
libclone-perl
libcloudproviders0
libclucene-contribs1v5
libclucene-core1v5
libcodec2-1.0
libcolamd2
libcolord2
libcolorhug2
libcom-err2
libcrypt1
libcrypt-dev
libcryptsetup12
libctf0
libctf-nobfd0
libcups2
libcupsfilters1
libcurl3-gnutls
libcurl4
libdaemon0
libdata-dump-perl
libdatrie1
libdav1d6
libdaxctl1
libdb5.3
libdbus-1-3
libdbus-glib-1-2
libdbusmenu-glib4
libdbusmenu-gtk3-4
libdc1394-25
libdca0
libdconf1
libde265-0
libdebconfclient0
libdecor-0-0
libdecor-0-plugin-1-cairo
libdeflate0
libdevmapper1.02.1
libdirectfb-1.7-7
libdjvulibre21
libdjvulibre-text
libdotconf0
libdouble-conversion3
libdpkg-perl
libdrm2
libdrm-amdgpu1
libdrm-common
libdrm-intel1
libdrm-nouveau2
libdrm-radeon1
libduktape207
libdv4
libdvdnav4
libdvdread8
libdw1
libeb16
libe-book-0.1-1
libedit2
libefiboot1
libefivar1
libegl1
libegl-mesa0
libelf1
libenchant-2-2
libenchant-2-voikko
libencode-locale-perl
libeot0
libepoxy0
libept1.6.0
libepubgen-0.1-1
liberror-perl
libespeak-ng1
libetonyek-0.1-1
libevdev2
libevent-2.1-7
libexecs0
libexif12
libexiv2-27
libexo-2-0
libexo-common
libexpat1
libext2fs2
libexttextcat-2.0-0
libexttextcat-data
libextutils-depends-perl
libfaad2
libfakeroot
libfcitx5config6
libfcitx5core7
libfcitx5-qt1
libfcitx5-qt-data
libfcitx5utils2
libfcitx-config4
libfcitx-core0
libfcitx-gclient1
libfcitx-qt5-1
libfcitx-qt5-data
libfcitx-utils0
libfdisk1
libfdt1
libffi8
libfftw3-double3
libfftw3-single3
libfido2-1
libfile-basedir-perl
libfile-desktopentry-perl
libfile-fcntllock-perl
libfile-listing-perl
libfile-mimeinfo-perl
libflac12
libflite1
libfluidsynth3
libfmt9
libfont-afm-perl
libfontconfig1
libfontembed1
libfontenc1
libfreeaptx0
libfreehand-0.1-1
libfreetype6
libfribidi0
libfuse2
libfuse3-3
libgail18
libgail-common
libgarcon-1-0
libgarcon-common
libgarcon-gtk3-1-0
libgav1-1
libgbm1
libgcc-12-dev
libgcc-s1
libgck-1-0
libgcr-base-3-1
libgcroots0
libgcr-ui-3-1
libgcrypt20
libgd3
libgdbm6
libgdbm-compat4
libgdk-pixbuf-2.0-0
libgdk-pixbuf2.0-bin
libgdk-pixbuf2.0-common
libgegl-0.4-0
libgegl-common
libgexiv2-2
libgfapi0
libgfortran5
libgfrpc0
libgfxdr0
libgif7
libgimp2.0
libgirepository-1.0-1
libgl1
libgl1-mesa-dri
libglapi-mesa
libgles2
libglib2.0-0
libglib2.0-data
libglibmm-2.4-1v5
libglib-object-introspection-perl
libglib-perl
libglu1-mesa
libglusterfs0
libglvnd0
libglx0
libglx-mesa0
libgme0
libgmp10
libgnutls30
libgnutls-dane0
libgomp1
libgpg-error0
libgpgme11
libgpgmepp6
libgphoto2-6
libgphoto2-l10n
libgphoto2-port12
libgpm2
libgprofng0
libgraphene-1.0-0
libgraphite2-3
libgs10
libgs10-common
libgs-common
libgsm1
libgspell-1-2
libgspell-1-common
libgssapi-krb5-2
libgssdp-1.6-0
libgstreamer1.0-0
libgstreamer-gl1.0-0
libgstreamer-plugins-bad1.0-0
libgstreamer-plugins-base1.0-0
libgtk2.0-0
libgtk2.0-bin
libgtk2.0-common
libgtk-3-0
libgtk-3-bin
libgtk-3-common
libgtk3-perl
libgtk-4-1
libgtk-4-bin
libgtk-4-common
libgtkmm-3.0-1v5
libgtksourceview-3.0-1
libgtksourceview-3.0-common
libgtksourceview-4-0
libgtksourceview-4-common
libgtop-2.0-11
libgtop2-common
libgudev-1.0-0
libgupnp-1.6-0
libgupnp-igd-1.0-4
libgusb2
libgxps2
libhandy-1-0
libhangul1
libhangul-data
libharfbuzz0b
libharfbuzz-icu0
libharfbuzz-subset0
libheif1
libhfstospell11
libhogweed6
libhtml-format-perl
libhtml-form-perl
libhtml-parser-perl
libhtml-tagset-perl
libhtml-tree-perl
libhttp-cookies-perl
libhttp-daemon-perl
libhttp-date-perl
libhttp-message-perl
libhttp-negotiate-perl
libhunspell-1.7-0
libhwy1
libhyphen0
libi2c0
libibus-1.0-5
libibverbs1
libice6
libice-dev
libicu72
libidn12
libidn2-0
libiec61883-0
libieee1284-3
libigdgmm12
libijs-0.35
libimath-3-1-29
libimecore0
libime-data
libime-data-language-model
libimepinyin0
libimetable0
libindi-data
libindidriver1
libinih1
libinput10
libinput-bin
libinstpatch-1.0-2
libintl-perl
libintl-xs-perl
libio-html-perl
libio-socket-ssl-perl
libio-stringy-perl
libip4tc2
libip6tc2
libipc-system-simple-perl
libiscsi7
libisl23
libisoburn1
libisofs6
libitm1
libiw30
libjack-jackd2-0
libjansson4
libjavascriptcoregtk-4.0-18
libjavascriptcoregtk-4.1-0
libjbig0
libjbig2dec0
libjim0.81
libjpeg62-turbo
libjs-jquery
libjs-mathjax
libjson-c5
libjsoncpp25
libjson-glib-1.0-0
libjson-glib-1.0-common
libjs-sphinxdoc
libjs-underscore
libjte2
libjxl0.7
libjxr0
libjxr-tools
libk5crypto3
libkate1
libkeybinder-3.0-0
libkeyutils1
libklibc
libkmod2
libkpathsea6
libkrb5-3
libkrb5support0
libksba8
liblangtag1
liblangtag-common
liblapack3
liblcms2-2
libldacbt-enc2
libldap-2.5-0
libldap-common
libldb2
liblerc4
liblightdm-gobject-1-0
liblilv-0-0
libllvm15
liblmdb0
liblocale-gettext-perl
liblockfile1
liblockfile-bin
liblouis20
liblouis-data
liblouisutdml9
liblouisutdml-bin
liblouisutdml-data
liblqr-1-0
liblrdf0
liblsan0
libltc11
libltdl7
liblua5.2-0
liblua5.3-0
liblwp-mediatypes-perl
liblwp-protocol-https-perl
liblz4-1
liblzma5
liblzo2-2
libm17n-0
libmagic1
libmagickcore-6.q16-6
libmagickcore-6.q16-6-extra
libmagickwand-6.q16-6
libmagic-mgc
libmailtools-perl
libmanette-0.2-0
libmarisa0
libmbedcrypto7
libmbim-glib4
libmbim-proxy
libmbim-utils
libmd0
libmd4c0
libmetis5
libmfx1
libmhash2
libminizip1
libmjpegutils-2.1-0
libmm-glib0
libmnl0
libmodplug1
libmodule-find-perl
libmodule-scandeps-perl
libmount1
libmousepad0
libmp3lame0
libmpc3
libmpcdec6
libmpeg2-4
libmpeg2encpp-2.1-0
libmpfr6
libmpg123-0
libmplex2-2.1-0
libmspub-0.1-1
libmtdev1
libmwaw-0.3-3
libmysofa1
libmythes-1.2-0
libncurses6
libncursesw6
libndctl6
libndp0
libneon27
libnet1
libnet-dbus-perl
libnetfilter-conntrack3
libnet-http-perl
libnet-smtp-ssl-perl
libnet-ssleay-perl
libnettle8
libnewt0.52
libnfnetlink0
libnfs13
libnftables1
libnftnl11
libnghttp2-14
libnice10
libnl-3-200
libnl-genl-3-200
libnl-route-3-200
libnm0
libnma0
libnma-common
libnorm1
libnotify4
libnotify-bin
libnova-0.16-0
libnpth0
libnsl2
libnsl-dev
libnspr4
libnss3
libnss-mdns
libnss-myhostname
libntfs-3g89
libnuma1
libnumbertext-1.0-0
libnumbertext-data
libodfgen-0.1-1
libogg0
libopenal1
libopenal-data
libopencc1.1
libopencc-data
libopencore-amrnb0
libopencore-amrwb0
libopenexr-3-1-30
libopengl0
libopenh264-7
libopenjp2-7
libopenmpt0
libopenni2-0
libopus0
liborc-0.4-0
liborcus-0.17-0
liborcus-parser-0.17-0
libotf1
libp11-kit0
libpackagekit-glib2-18
libpagemaker-0.0-0
libpam0g
libpam-gnome-keyring
libpam-modules
libpam-modules-bin
libpam-runtime
libpam-systemd
libpango-1.0-0
libpangocairo-1.0-0
libpangoft2-1.0-0
libpangomm-1.4-1v5
libpangoxft-1.0-0
libpaper1
libpaper-utils
libparted2
libparted-fs-resize0
libpcap0.8
libpcaudio0
libpci3
libpciaccess0
libpcre2-16-0
libpcre2-8-0
libpcre3
libpcsclite1
libperl5.36
libpgm-5.3-0
libpipeline1
libpipewire-0.3-0
libpipewire-0.3-common
libpixman-1-0
libplacebo208
libplymouth5
libpmem1
libpng16-16
libpocketsphinx3
libpolkit-agent-1-0
libpolkit-gobject-1-0
libpoppler126
libpoppler-cpp0v5
libpoppler-glib8
libpopt0
libpostproc56
libpresage1v5
libpresage-data
libproc2-0
libproc-processtable-perl
libprotobuf32
libprotobuf-c1
libproxy1v5
libpsl5
libpthread-stubs0-dev
libpulse0
libpulsedsp
libpulse-mainloop-glib0
libpython3.11
libpython3.11-minimal
libpython3.11-stdlib
libpython3-stdlib
libqmi-glib5
libqmi-proxy
libqmi-utils
libqpdf29
libqrencode4
libqrtr-glib0
libqt5core5a
libqt5dbus5
libqt5gui5
libqt5help5
libqt5multimedia5
libqt5multimedia5-plugins
libqt5multimediagsttools5
libqt5multimediawidgets5
libqt5network5
libqt5positioning5
libqt5printsupport5
libqt5qml5
libqt5qmlmodels5
libqt5quick5
libqt5quickwidgets5
libqt5sensors5
libqt5sql5
libqt5sql5-sqlite
libqt5svg5
libqt5waylandclient5
libqt5waylandcompositor5
libqt5webchannel5
libqt5webenginecore5
libqt5webengine-data
libqt5webenginewidgets5
libqt5webkit5
libqt5widgets5
libqt5x11extras5
libqt5xml5
libquadmath0
libqxp-0.0-0
librabbitmq4
librados2
libraptor2-0
librasqal3
librav1e0
libraw1394-11
libraw20
librbd1
librdf0
librdmacm1
libre2-9
libreadline8
librecode0
libregexp-ipv6-perl
librevenge-0.0-0
librist4
librsvg2-2
librsvg2-common
librtmp1
librubberband2
libsamplerate0
libsane1
libsane-common
libsasl2-2
libsasl2-modules
libsasl2-modules-db
libsbc1
libsdl2-2.0-0
libseccomp2
libsecret-1-0
libsecret-common
libselinux1
libsemanage2
libsemanage-common
libsensors5
libsensors-config
libsepol2
libserd-0-0
libshine3
libshout3
libsidplay1v5
libsigc++-2.0-0v5
libslang2
libslirp0
libsm6
libsmartcols1
libsmbclient
libsm-dev
libsnappy1v5
libsndfile1
libsndio7.0
libsnmp40
libsnmp-base
libsodium23
libsonic0
libsord-0-0
libsort-naturally-perl
libsoundtouch1
libsoup2.4-1
libsoup2.4-common
libsoup-3.0-0
libsoup-3.0-common
libsoup-gnome2.4-1
libsoxr0
libspa-0.2-modules
libspandsp2
libspectre1
libspeechd2
libspeex1
libspeexdsp1
libsphinxbase3
libspice-server1
libsqlite3-0
libsratom-0-0
libsrt1.5-gnutls
libsrtp2-1
libss2
libssh2-1
libssh-4
libssh-gcrypt-4
libssl3
libstartup-notification0
libstdc++-12-dev
libstdc++6
libsuitesparseconfig5
libsvtav1enc1
libswresample4
libswscale6
libsynctex2
libsystemd0
libsystemd-shared
libtag1v5
libtag1v5-vanilla
libtagc0
libtalloc2
libtasn1-6
libtdb1
libteamdctl0
libterm-readkey-perl
libtevent0
libtext-charwidth-perl
libtext-iconv-perl
libtext-wrapi18n-perl
libthai0
libthai-data
libtheora0
libthunarx-3-0
libtie-ixhash-perl
libtiff6
libtimedate-perl
libtinfo6
libtinyxml2.6.2v5
libtirpc3
libtirpc-common
libtirpc-dev
libtry-tiny-perl
libtsan2
libtumbler-1-0
libtwolame0
libu2f-udev
libubsan1
libuchardet0
libudev1
libudfread0
libudisks2-0
libuim8
libuim-custom2
libuim-data
libuim-scm0
libumfpack5
libunbound8
libunistring2
libuno-cppu3
libuno-cppuhelpergcc3-3
libuno-purpenvhelpergcc3-3
libuno-sal3
libuno-salhelpergcc3-3
libunwind8
libupower-glib3
liburcu8
liburing2
liburi-perl
libusb-1.0-0
libusbredirparser1
libutempter0
libuuid1
libv4l-0
libv4lconvert0
libva2
libva-drm2
libva-x11-2
libvdeplug2
libvdpau1
libvdpau-va-gl1
libvidstab1.1
libvirglrenderer1
libvisio-0.1-1
libvisual-0.4-0
libvo-aacenc0
libvo-amrwbenc0
libvoikko1
libvolume-key1
libvorbis0a
libvorbisenc2
libvorbisfile3
libvpx7
libvte-2.91-0
libvte-2.91-common
libvulkan1
libwacom9
libwacom-common
libwavpack1
libwayland-client0
libwayland-cursor0
libwayland-egl1
libwayland-server0
libwbclient0
libwebkit2gtk-4.0-37
libwebkit2gtk-4.1-0
libwebp7
libwebpdemux2
libwebpmux3
libwebrtc-audio-processing1
libwildmidi2
libwmflite-0.2-7
libwnck-3-0
libwnck-3-common
libwoff1
libwpd-0.10-10
libwpe-1.0-1
libwpebackend-fdo-1.0-1
libwpg-0.3-3
libwps-0.4-4
libwrap0
libwww-perl
libwww-robotrules-perl
libx11-6
libx11-data
libx11-dev
libx11-protocol-perl
libx11-xcb1
libx264-164
libx265-199
libx86-1
libxapian30
libxatracker2
libxau6
libxau-dev
libxaw7
libxcb1
libxcb1-dev
libxcb-damage0
libxcb-dri2-0
libxcb-dri3-0
libxcb-ewmh2
libxcb-glx0
libxcb-icccm4
libxcb-image0
libxcb-imdkit1
libxcb-keysyms1
libxcb-present0
libxcb-randr0
libxcb-render0
libxcb-render-util0
libxcb-shape0
libxcb-shm0
libxcb-sync1
libxcb-util1
libxcb-xfixes0
libxcb-xinerama0
libxcb-xinput0
libxcb-xkb1
libxcomposite1
libxcursor1
libxcvt0
libxdamage1
libxdmcp6
libxdmcp-dev
libxext6
libxfce4panel-2.0-4
libxfce4ui-2-0
libxfce4ui-common
libxfce4ui-utils
libxfce4util7
libxfce4util-bin
libxfce4util-common
libxfconf-0-3
libxfixes3
libxfont2
libxft2
libxi6
libxinerama1
libxkbcommon0
libxkbcommon-x11-0
libxkbfile1
libxklavier16
libxml2
libxml-parser-perl
libxmlsec1
libxmlsec1-nss
libxml-twig-perl
libxml-xpathengine-perl
libxmu6
libxmuu1
libxnvctrl0
libxpm4
libxpresent1
libxrandr2
libxrender1
libxres1
libxshmfence1
libxslt1.1
libxss1
libxt6
libxtables12
libxt-dev
libxtst6
libxv1
libxvidcore4
libxvmc1
libxxf86dga1
libxxf86vm1
libxxhash0
libyajl2
libyaml-0-2
libyuv0
libz3-4
libzbar0
libzimg2
libzmf-0.0-0
libzmq5
libzstd1
libzvbi0
libzvbi-common
libzxing2
lightdm
lightdm-gtk-greeter
light-locker
linux-base
linux-compiler-gcc-12-x86
linux-headers-6.1.0-15-amd64
linux-headers-6.1.0-15-common
linux-image-6.1.0-15-amd64
linux-image-6.1.0-16-amd64
linux-image-amd64
linux-kbuild-6.1
linux-libc-dev
lm-sensors
locales
login
logrotate
logsave
lp-solve
lsb-release
lsof
lynx
lynx-common
m17n-db
mailcap
make
man-db
manpages
manpages-dev
mawk
mdadm
media-types
mesa-utils
mesa-utils-bin
mesa-va-drivers
mesa-vdpau-drivers
mesa-vulkan-drivers
mlterm
mlterm-common
mlterm-tools
mobile-broadband-provider-info
modemmanager
mokutil
mount
mousepad
mozc-data
mozc-server
mozc-utils-gui
mtools
myspell-eo
myspell-es
myspell-et
myspell-fa
myspell-ga
myspell-he
myspell-nb
myspell-nn
myspell-sk
myspell-sq
myspell-uk
mythes-cs
mythes-de
mythes-de-ch
mythes-en-us
mythes-fr
mythes-it
mythes-ne
mythes-pl
mythes-ru
mythes-sk
nano
ncurses-base
ncurses-bin
ncurses-term
needrestart
netbase
network-manager
network-manager-gnome
nftables
node-clipboard
node-normalize.css
node-prismjs
ntfs-3g
ocl-icd-libopencl1
openjdk-17-jdk
openjdk-17-jdk-headless
openjdk-17-jre
openjdk-17-jre-headless
openssh-client
openssl
orca
os-prober
ovmf
p11-kit
p11-kit-modules
p7zip
p7zip-full
parole
parted
passwd
patch
pavucontrol
pci.ids
pciutils
perl
perl-base
perl-modules-5.36
perl-openssl-defaults
perl-tk
pinentry-curses
pinentry-gnome3
pkexec
plymouth
plymouth-label
pocketsphinx-en-us
policykit-1
policykit-1-gnome
polkitd
polkitd-pkla
poppler-data
poppler-utils
powermgmt-base
ppp
presage
procps
psf-unifont
psmisc
publicsuffix
pulseaudio
pulseaudio-utils
python3
python3.11
python3.11-minimal
python3-attr
python3-brlapi
python3-cairo
python3-certifi
python3-chardet
python3-charset-normalizer
python3-cups
python3-cupshelpers
python3-dbus
python3-distro
python3-distutils
python3-docker
python3-dockerpty
python3-docopt
python3-dotenv
python3-feedparser
python3-gi
python3-gi-cairo
python3-ibus-1.0
python3-idna
python3-json-pointer
python3-jsonschema
python3-lib2to3
python3-libvoikko
python3-louis
python3-minimal
python3-musicbrainzngs
python3-mutagen
python3-pkg-resources
python3-protobuf
python3-pyatspi
python3-pyinotify
python3-pyrsistent
python3-requests
python3-rfc3987
python3-sgmllib3k
python3-six
python3-smbc
python3-speechd
python3-texttable
python3-uno
python3-uritemplate
python3-urllib3
python3-webcolors
python3-websocket
python3-xdg
python3-yaml
qemu-block-extra
qemu-system-common
qemu-system-data
qemu-system-gui
qemu-system-x86
qemu-utils
qt5-gtk-platformtheme
qttranslations5-l10n
qtwayland5
quodlibet
read-edid
readline-common
ristretto
rpcsvc-proto
rsync
rtkit
runc
samba-libs
sane-airscan
sane-utils
seabios
sed
sensible-utils
sgml-base
shared-mime-info
shim-helpers-amd64-signed
shim-signed
shim-signed-common
shim-unsigned
sound-icons
sound-theme-freedesktop
speech-dispatcher
speech-dispatcher-audio-plugins
speech-dispatcher-espeak-ng
sphinx-rtd-theme-common
squashfs-tools
ssl-cert
sudo
synaptic
syslinux-common
syslinux-efi
system-config-printer
system-config-printer-common
system-config-printer-udev
systemd
systemd-sysv
sysvinit-utils
t1-cyrillic
t1-teams
tango-icon-theme
tar
thunar
thunar-archive-plugin
thunar-data
thunar-media-tags-plugin
thunar-volman
timgm6mb-soundfont
tini
tumbler
tumbler-common
tzdata
ucf
udev
udisks2
uim
uim-data
uim-fep
uim-gtk2.0
uim-gtk2.0-immodule
uim-gtk3
uim-gtk3-immodule
uim-mozc
uim-plugins
uim-qt5
uim-qt5-immodule
uim-xim
unifont
uno-libs-private
unzip
update-inetd
upower
ure
usb.ids
usb-modeswitch
usb-modeswitch-data
usr-is-merged
util-linux
util-linux-extra
util-linux-locales
uuid-runtime
va-driver-all
vdpau-driver-all
vim
vim-common
vim-runtime
vim-tiny
voikko-fi
wamerican
wbrazilian
wbulgarian
wcatalan
wdanish
wdutch
wfrench
wget
whiptail
wireless-regdb
wireless-tools
witalian
wngerman
wnorwegian
wpasupplicant
wpolish
wportuguese
wspanish
wswedish
x11-apps
x11-common
x11proto-dev
x11-session-utils
x11-utils
x11-xkb-utils
x11-xserver-utils
xarchiver
xauth
xbitmaps
xbrlapi
xcvt
xdg-dbus-proxy
xdg-desktop-portal
xdg-desktop-portal-gtk
xdg-user-dirs
xdg-utils
xfburn
xfce4
xfce4-appfinder
xfce4-battery-plugin
xfce4-clipman
xfce4-clipman-plugin
xfce4-cpufreq-plugin
xfce4-cpugraph-plugin
xfce4-dict
xfce4-diskperf-plugin
xfce4-fsguard-plugin
xfce4-genmon-plugin
xfce4-goodies
xfce4-helpers
xfce4-mailwatch-plugin
xfce4-netload-plugin
xfce4-notifyd
xfce4-panel
xfce4-places-plugin
xfce4-power-manager
xfce4-power-manager-data
xfce4-power-manager-plugins
xfce4-pulseaudio-plugin
xfce4-screenshooter
xfce4-sensors-plugin
xfce4-session
xfce4-settings
xfce4-smartbookmark-plugin
xfce4-systemload-plugin
xfce4-taskmanager
xfce4-terminal
xfce4-timer-plugin
xfce4-verve-plugin
xfce4-wavelan-plugin
xfce4-weather-plugin
xfce4-whiskermenu-plugin
xfce4-xkb-plugin
xfconf
xfdesktop4
xfdesktop4-data
xfonts-100dpi
xfonts-75dpi
xfonts-base
xfonts-encodings
xfonts-scalable
xfonts-thai
xfonts-thai-etl
xfonts-thai-manop
xfonts-thai-nectec
xfonts-thai-poonlap
xfonts-thai-vor
xfonts-unifont
xfonts-utils
xfsprogs
xfwm4
xiccd
xinit
xinput
xiterm+thai
xkb-data
xkbset
xml-core
xorg
xorg-docs-core
xorg-sgml-doctools
xorriso
xsane
xsane-common
xserver-common
xserver-xorg
xserver-xorg-core
xserver-xorg-input-all
xserver-xorg-input-libinput
xserver-xorg-input-wacom
xserver-xorg-legacy
xserver-xorg-video-all
xserver-xorg-video-amdgpu
xserver-xorg-video-ati
xserver-xorg-video-fbdev
xserver-xorg-video-intel
xserver-xorg-video-nouveau
xserver-xorg-video-qxl
xserver-xorg-video-radeon
xserver-xorg-video-vesa
xserver-xorg-video-vmware
xterm
xtrans-dev
xxkb
xz-utils
zenity
zenity-common
zlib1g
zstd


